language: python

sudo: false

cache: pip

python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - DJANGO='https://github.com/django/django/archive/master.tar.gz'
  - DJANGO='django>=1.10.0,<1.11.0'
  - DJANGO='django>=1.9.0,<1.10.0'
  - DJANGO='django>=1.8.0,<1.9.0'

install:
  - travis_retry pip install $DJANGO
  - travis_retry pip install -r requirements/travis-ci.txt

script:
  - coverage run --source django_filters runtests.py -v 2
  - coverage report

notifications:
  email: false

matrix:
  exclude:
    - python: "3.3"
      env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
    - python: "3.3"
      env: DJANGO='django>=1.10.0,<1.11.0'
    - python: "3.3"
      env: DJANGO='django>=1.9.0,<1.10.0'
  allow_failures:
    - env: DJANGO='https://github.com/django/django/archive/master.tar.gz'
  fast_finish: true
